[build-system]
# Remove this pin when pypa/twine supports core metadata 2.4
# hynek/build-and-inspect-python-package runs `twine check`
# which is causing the release CI to fail
requires = ["setuptools>=69.0,<81.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cqm"
version = "0.1.0"
dependencies = [
    "dimod~=0.12.0",
    "dwave-ocean-sdk~=9.2.0",
    "matplotlib~=3.10.0"
]
requires-python = ">=3.10, <3.13"
authors = [
  {name = "Amir Ali Malekani Nezhad", email = "amiralimlk07@gmail.com"}
]
maintainers = [
  {name = "Amir Ali Malekani Nezhad", email = "amiralimlk07@gmail.com"}
]
description = "Hybrid Quantum Annealing solution for Vehicle Routing Problem (VRP)."
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["quantum annealing", "quantum optimization", "quantum combinatorial optimization", "vrp"]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent"
]

[project.optional-dependencies]
dev = [
  "ruff == 0.11.7",
  "mypy == 1.15.0",
  "pytest == 8.3.5",
  "pytest-mock == 3.14.0",
  "pytest-cov == 6.1.1",
  "coverage == 7.8.0",
]

[project.urls]
Repository = "https://github.com/ACE07-Sev/CQM-TSP.git"
"Bug Tracker" = "https://github.com/ACE07-Sev/CQM-TSP/issues"

[tool.setuptools.packages.find]
include = ["cqm*"]

[tool.setuptools.package-data]
"cqm" = ["py.typed"]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.codeflash]
# All paths are relative to this pyproject.toml's directory.
module-root = "cqm"
tests-root = "tests"
test-framework = "pytest"
ignore-paths = []
formatter-cmds = ["disabled"]